# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Shawn Cole"
description: "Experienced iOS Developer & Software Engineer"
baseurl: "" # the subpath of your site, e.g∂ /blog
#url: "https://shawncole.dev" # replace with your domain

#theme: "minimal-mistakes-jekyll"
remote_theme: minimal-mistakes-jekyll

domain: Cole9350.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://Cole9350.github.io  # the base hostname and protocol for your site, e.g. http://example.com

author:
  name: Shawn Cole
  avatar: "https://media.licdn.com/dms/image/D4E35AQG_og3JtWu_qA/profile-framedphoto-shrink_200_200/0/1716219796068?e=1716847200&v=beta&t=fwB4wkkbD4-sVqVM105zFWYxBia-H9illrXrGSZdptM"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/shawn-cole-332187a5/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Cole9350"
    - label: "Stack Overflow"
      icon: "fab fa-stack-overflow"
      url: "https://stackoverflow.com/users/1530004/cole9350"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-avatar
  - jekyll-include-cache

# Other configuration options...


#title: Your awesome title
#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
